import type { Metadata } from "next";
import "./globals.css";
import MinLayout from "@/components/main"
import Header from "@/components/Header"
import Aside from "@/components/Aside"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
       <div className="flex flex-col h-[100vh]">
       <Header/>
        <div className="flex">
        <Aside/>
        <MinLayout>{children}</MinLayout>
        </div>
       </div>
      </body>
    </html>
  );
}
